## Lstm基本方法

In [107]:
import torch
import torch.nn as nn             # 神经网络模块

In [108]:
#输入一个三维向量，序列长度是5，batchsize的大小是3，数据的维度是10
input = torch.randn(5, 3, 10)
input

tensor([[[-2.9887e-01, -1.0906e+00, -3.2491e-01,  9.0450e-01,  8.6962e-01,
           5.8029e-01,  5.9709e-01,  2.2211e-01,  1.6019e+00, -3.0774e-01],
         [-1.3165e+00, -5.5317e-01, -2.4624e-01,  2.3981e-01, -1.6486e+00,
           2.2165e+00,  4.2184e-01,  4.2397e-01, -1.1512e+00,  2.1666e+00],
         [-1.1043e+00,  5.1162e-01, -2.1645e+00, -6.2635e-02, -1.7110e+00,
           2.6152e-01,  6.1497e-01, -2.4625e+00, -6.0482e-02, -2.3050e-01]],

        [[ 6.6064e-01,  2.2689e+00,  3.5934e+00, -3.1203e-01, -9.8808e-01,
           1.2020e+00,  2.3271e-02,  7.8549e-01, -2.6834e-01, -1.1233e+00],
         [-4.3374e-01, -4.7572e-01,  2.0592e+00,  5.3663e-02, -7.8212e-01,
           7.0176e-01,  6.8634e-01, -4.3126e-01,  7.9296e-01,  8.9293e-01],
         [-5.3938e-01,  2.0193e+00,  1.6906e-01,  3.9988e-01,  2.4367e-01,
           4.1347e-01, -1.2240e+00,  2.8946e-03, -8.5198e-01, -7.9133e-01]],

        [[ 5.4147e-01, -3.3297e-01,  1.3279e-01,  1.6706e+00,  1.5328e+00,
           6.36

In [109]:
input.shape

torch.Size([5, 3, 10])

In [110]:
#定义这个神经网络的输入维度10，输出维度是20，有2层
rnn = nn.LSTM(10, 20, 2) 

In [111]:
#这里定义隐藏层有2层，batchsize是3，数据输出维度20
h_0 = torch.randn(2, 3, 20)
#这里定义细胞结构有2层，batchsize是3，数据输出维度20
c_0 = torch.randn(2, 3, 20)


In [112]:
output, (h_n,c_n)= rnn(input, (h_0, c_0))

In [113]:
print(output.shape)
output

torch.Size([5, 3, 20])


tensor([[[ 0.3604,  0.5154,  0.0711, -0.2352, -0.3483,  0.3091, -0.1215,
          -0.0475, -0.0412, -0.3772,  0.0706,  0.1233, -0.1183,  0.3506,
           0.1431,  0.5162, -0.1927, -0.3727, -0.0917,  0.2457],
         [ 0.5643,  0.2944, -0.1171, -0.6255,  0.1865, -0.5595, -0.2428,
          -0.1065, -0.1247, -0.1740, -0.1951,  0.4056,  0.2493,  0.1001,
           0.4570,  0.2602, -0.3528,  0.1118, -0.3984,  0.2136],
         [-0.0215,  0.4137,  0.3563,  0.3736, -0.2950, -0.3326,  0.0533,
           0.0849, -0.4866,  0.1907, -0.3113, -0.2270, -0.0584, -0.0878,
           0.1643, -0.0978, -0.0408,  0.1756, -0.1073,  0.4127]],

        [[ 0.2799,  0.2577,  0.0685, -0.2101, -0.1080,  0.2490, -0.1663,
          -0.0728,  0.0122, -0.1475,  0.1249,  0.0437, -0.0843,  0.2203,
           0.0721,  0.1660, -0.1027, -0.2771, -0.0479,  0.1159],
         [ 0.2275,  0.2957, -0.0434, -0.3822,  0.0813, -0.2542, -0.2015,
          -0.1910, -0.1532, -0.1752, -0.1095,  0.0989,  0.0791,  0.0142,
        

In [114]:
print(h_n.shape)
h_n

torch.Size([2, 3, 20])


tensor([[[ 0.2534,  0.1517, -0.2272, -0.2379,  0.0810, -0.1336,  0.2135,
          -0.0892,  0.0149,  0.2816, -0.1149,  0.0479,  0.0180,  0.0805,
          -0.2502,  0.1231,  0.0006, -0.0087, -0.0048, -0.0820],
         [ 0.0600,  0.1964,  0.0666,  0.0105,  0.2475,  0.1037,  0.2565,
          -0.0217, -0.1633,  0.2251, -0.1423, -0.1041,  0.1163, -0.0169,
          -0.1894,  0.0076, -0.2073,  0.1783,  0.0453,  0.1975],
         [ 0.0736,  0.1269,  0.0633,  0.1144,  0.1661, -0.1076,  0.1930,
           0.0030, -0.0846,  0.1921, -0.0753,  0.0608,  0.1503,  0.0682,
          -0.0943, -0.0614, -0.1420,  0.1475,  0.2195,  0.0525]],

        [[ 0.2321,  0.1606,  0.0823, -0.0938,  0.1104, -0.0658, -0.1930,
          -0.0301, -0.0101,  0.0679,  0.0693, -0.0351, -0.0172,  0.0948,
           0.0146, -0.0371, -0.0874, -0.1333, -0.0089, -0.0920],
         [ 0.1959,  0.1301,  0.0259, -0.1169,  0.1337, -0.0944, -0.1091,
          -0.0968, -0.1086,  0.0367, -0.0304, -0.0313, -0.0202,  0.0352,
        

In [115]:
c_n.shape

torch.Size([2, 3, 20])

In [116]:
c_n.size()

torch.Size([2, 3, 20])

In [117]:
c_n.size(0)

2

## lstm实例

In [118]:
import torch 
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms

In [119]:
# 定义一个设备
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [120]:
# 定义超参数
sequence_length = 28
input_size = 28
hidden_size = 128
num_layers = 2
num_classes = 10
batch_size = 100
num_epochs = 2
learning_rate = 0.01

In [121]:
# 下载训练数据和测试数据
train_dataset = torchvision.datasets.MNIST(root='./data/',
                                           train=True, 
                                           transform=transforms.ToTensor(),
                                           download=True)
test_dataset = torchvision.datasets.MNIST(root='./data/',
                                            train=False, 
                                            transform=transforms.ToTensor(),
                                            download=False)

In [122]:
train_dataset.classes

['0 - zero',
 '1 - one',
 '2 - two',
 '3 - three',
 '4 - four',
 '5 - five',
 '6 - six',
 '7 - seven',
 '8 - eight',
 '9 - nine']

In [123]:
# 加载数据
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                           batch_size=batch_size, 
                                           shuffle=True)
 
test_loader = torch.utils.data.DataLoader(dataset=test_dataset,
                                          batch_size=batch_size, 
                                          shuffle=False)


In [124]:
#定义神经网络
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super(RNN, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, num_classes)
        
    def forward(self, x):
        # Set initial hidden and cell states 
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device) 
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)
        
        # Forward propagate LSTM
        out, (h_n,c_n) = self.lstm(x, (h0, c0))  # out: tensor of shape (batch_size, seq_length, hidden_size)
        
        # Decode the hidden state of the last time step
        out = self.fc(out[:, -1, :])# 此处的-1说明我们只取RNN最后输出的那个hn
        return out


In [125]:
model = RNN(input_size, hidden_size, num_layers, num_classes).to(device)

In [126]:
#定义损失函数和优化器
# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)


In [128]:
# 训练模型
model.train()
total_step = len(train_loader)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
        images = images.reshape(-1, sequence_length, input_size).to(device)
        labels = labels.to(device)
        
        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)
        
        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, i+1, total_step, loss.item()))


Epoch [1/2], Step [100/600], Loss: 0.6730
Epoch [1/2], Step [200/600], Loss: 0.4397
Epoch [1/2], Step [300/600], Loss: 0.2468
Epoch [1/2], Step [400/600], Loss: 0.2396
Epoch [1/2], Step [500/600], Loss: 0.2224
Epoch [1/2], Step [600/600], Loss: 0.1711
Epoch [2/2], Step [100/600], Loss: 0.1211
Epoch [2/2], Step [200/600], Loss: 0.0603
Epoch [2/2], Step [300/600], Loss: 0.0458
Epoch [2/2], Step [400/600], Loss: 0.1313
Epoch [2/2], Step [500/600], Loss: 0.1638
Epoch [2/2], Step [600/600], Loss: 0.0613


In [129]:
# 测试模型
model.eval()
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in test_loader:
        images = images.reshape(-1, sequence_length, input_size).to(device)
        labels = labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()
 
    print('Test Accuracy of the model on the 10000 test images: {} %'.format(100 * correct / total)) 



Test Accuracy of the model on the 10000 test images: 97.54 %
