## where 方法

In [1]:
import torch

In [2]:
cond = torch.randn(2,2)
cond

tensor([[ 2.0339,  0.1789],
        [-1.9342,  0.5747]])

In [3]:
cond>0

tensor([[ True,  True],
        [False,  True]])

In [5]:
a = torch.zeros(2,2)
a

tensor([[0., 0.],
        [0., 0.]])

In [6]:
b = torch.ones(2,2)
b

tensor([[1., 1.],
        [1., 1.]])

In [7]:
torch.where(cond>0,a,b) ##这里如果有GPU，则表示在GPU上运行

tensor([[0., 0.],
        [1., 0.]])

## gather 使用方法

In [9]:
prob = torch.randn(4,10)
prob

tensor([[ 0.9416, -0.3350,  0.0113,  0.1867, -1.7535,  0.2838,  0.8314, -0.1710,
         -0.1500,  1.5058],
        [ 0.4292,  1.3495, -1.0651, -0.2327, -0.1672,  0.0474, -0.9597, -0.4437,
         -0.5019, -0.5166],
        [-0.8929, -1.7386,  1.0660,  0.5420,  1.2027,  0.2687, -1.3452, -1.7792,
          0.0183, -1.8726],
        [ 0.0442, -0.1774,  0.4676, -0.9637, -0.3263, -0.1462, -0.8687, -0.0086,
         -0.2793,  0.8545]])

In [11]:
idx = prob.topk(dim =1,k = 3)

In [12]:
idx

torch.return_types.topk(
values=tensor([[1.5058, 0.9416, 0.8314],
        [1.3495, 0.4292, 0.0474],
        [1.2027, 1.0660, 0.5420],
        [0.8545, 0.4676, 0.0442]]),
indices=tensor([[9, 0, 6],
        [1, 0, 5],
        [4, 2, 3],
        [9, 2, 0]]))

In [13]:
idx[1]

tensor([[9, 0, 6],
        [1, 0, 5],
        [4, 2, 3],
        [9, 2, 0]])

In [16]:
label = torch.arange(10)+100
label

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [17]:
label.expand(4,10)

tensor([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [20]:
torch.gather(label.expand(4,10),dim=1,index = idx[1]) #主要是做映射方法

tensor([[109, 100, 106],
        [101, 100, 105],
        [104, 102, 103],
        [109, 102, 100]])